chcp 65001
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ア_left.png" "ア_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ア_right.png" "ア_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="カ_left.png" "カ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="カ_right.png" "カ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="サ_left.png" "サ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="サ_right.png" "サ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="タ_left.png" "タ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="タ_right.png" "タ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ナ_left.png" "ナ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ナ_right.png" "ナ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_left.png" "ハ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ハ_right.png" "ハ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="マ_left.png" "マ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="マ_right.png" "マ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ヤ_left.png" "ヤ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ヤ_right.png" "ヤ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ラ_left.png" "ラ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ラ_right.png" "ラ_right.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ワ_left.png" "ワ_left.svg"
"C:\Program Files\Inkscape\bin\inkscape" --export-background-opacity=0 --export-width=4838 --export-type=png --export-filename="ワ_right.png" "ワ_right.svg"
pause
exit